import type {
  User,
  Course,
  Module,
  Homework,
  CourseGrades,
  UserStatistics,
  Achievement,
  Activity,
  DashboardData,
  ProgressDataPoint,
} from '../types';
import type { SliderItem } from '../components/shared';

export const mockUser: User = {
  id: '1',
  email: 'ivan@student.ru',
  firstName: 'Иван',
  lastName: 'Иванов',
  patronymic: 'Иванович',
  avatar: 'https://i.pravatar.cc/150?img=12',
  phone: '+7 (999) 123-45-67',
  birthDate: '2000-01-01',
  country: 'Россия',
  city: 'Москва',
  bio: 'Студент 3 курса, изучаю программирование...',
  role: 'student',
  registeredAt: '2025-09-01T00:00:00Z',
};

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Python для начинающих',
    description: 'Изучите основы Python и научитесь писать код',
    coverImage: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800',
    teacherId: 't1',
    teacherName: 'Андрей Петров',
    teacherAvatar: 'https://i.pravatar.cc/150?img=33',
    progress: 65,
    totalModules: 4,
    completedModules: 2,
    isActive: true,
    startDate: '2025-09-01T00:00:00Z',
    averageGrade: 82,
    category: 'Программирование',
    duration: 40,
    difficulty: 'beginner',
    rating: 4.8,
    studentsCount: 2543,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Web-разработка',
    description: 'HTML, CSS, JavaScript - создайте свой первый сайт',
    coverImage: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800',
    teacherId: 't2',
    teacherName: 'Мария Сидорова',
    teacherAvatar: 'https://i.pravatar.cc/150?img=44',
    progress: 40,
    totalModules: 5,
    completedModules: 2,
    isActive: true,
    startDate: '2025-10-01T00:00:00Z',
    averageGrade: 88,
    category: 'Программирование',
    duration: 60,
    difficulty: 'beginner',
    rating: 4.6,
    studentsCount: 3201,
    createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '3',
    title: 'SQL Основы',
    description: 'Работа с базами данных и SQL запросами',
    coverImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800',
    teacherId: 't3',
    teacherName: 'Ольга Иванова',
    teacherAvatar: 'https://i.pravatar.cc/150?img=20',
    progress: 75,
    totalModules: 3,
    completedModules: 2,
    isActive: true,
    startDate: '2025-08-15T00:00:00Z',
    averageGrade: 95,
    category: 'Data Science',
    duration: 25,
    difficulty: 'beginner',
    rating: 4.9,
    studentsCount: 1890,
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'React Advanced',
    description: 'Продвинутые техники разработки на React',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
    teacherId: 't1',
    teacherName: 'Андрей Петров',
    progress: 0,
    totalModules: 8,
    completedModules: 0,
    isActive: false,
    startDate: '2025-11-01T00:00:00Z',
    category: 'Программирование',
    duration: 80,
    difficulty: 'advanced',
    rating: 4.7,
    studentsCount: 980,
    createdAt: '2025-10-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Основы UI/UX дизайна',
    description: 'Научитесь создавать красивые и удобные интерфейсы',
    coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    teacherId: 't4',
    teacherName: 'Елена Смирнова',
    progress: 0,
    totalModules: 6,
    completedModules: 0,
    isActive: false,
    startDate: '2025-11-15T00:00:00Z',
    category: 'Дизайн',
    duration: 35,
    difficulty: 'beginner',
    rating: 4.5,
    studentsCount: 1567,
    createdAt: '2024-05-01T00:00:00Z',
  },
  {
    id: '6',
    title: 'Цифровой маркетинг',
    description: 'Продвижение бизнеса в интернете',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    teacherId: 't5',
    teacherName: 'Дмитрий Козлов',
    progress: 0,
    totalModules: 7,
    completedModules: 0,
    isActive: false,
    startDate: '2025-12-01T00:00:00Z',
    category: 'Маркетинг',
    duration: 45,
    difficulty: 'intermediate',
    rating: 4.4,
    studentsCount: 2103,
    createdAt: '2024-06-12T00:00:00Z',
  },
  {
    id: '7',
    title: 'Управление проектами',
    description: 'Agile, Scrum и эффективное управление командой',
    coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    teacherId: 't6',
    teacherName: 'Сергей Волков',
    progress: 0,
    totalModules: 5,
    completedModules: 0,
    isActive: false,
    startDate: '2025-12-10T00:00:00Z',
    category: 'Бизнес',
    duration: 30,
    difficulty: 'intermediate',
    rating: 4.6,
    studentsCount: 1234,
    createdAt: '2024-07-20T00:00:00Z',
  },
  {
    id: '8',
    title: 'Machine Learning с Python',
    description: 'Введение в машинное обучение и нейронные сети',
    coverImage: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800',
    teacherId: 't7',
    teacherName: 'Алексей Морозов',
    progress: 0,
    totalModules: 10,
    completedModules: 0,
    isActive: false,
    startDate: '2026-01-05T00:00:00Z',
    category: 'Data Science',
    duration: 120,
    difficulty: 'advanced',
    rating: 4.9,
    studentsCount: 756,
    createdAt: '2025-11-15T00:00:00Z',
  },
];

export const mockModules: Module[] = [
  // Python курс
  {
    id: 'm1',
    courseId: '1',
    title: 'Основы Python',
    order: 1,
    totalLessons: 4,
    completedLessons: 4,
    isExpanded: true,
    lessons: [
      {
        id: 'l1',
        moduleId: 'm1',
        title: 'Введение в Python',
        type: 'video',
        duration: '10:30',
        status: 'completed',
        order: 1,
        videoUrl: 'https://example.com/video1.mp4',
      },
      {
        id: 'l2',
        moduleId: 'm1',
        title: 'Установка и настройка',
        type: 'video',
        duration: '15:20',
        status: 'completed',
        order: 2,
      },
      {
        id: 'l3',
        moduleId: 'm1',
        title: 'Первая программа',
        type: 'practice',
        duration: '20:15',
        status: 'completed',
        order: 3,
      },
      {
        id: 'l4',
        moduleId: 'm1',
        title: 'Тест: Основы Python',
        type: 'test',
        status: 'completed',
        order: 4,
      },
    ],
  },
  {
    id: 'm2',
    courseId: '1',
    title: 'Переменные и типы данных',
    order: 2,
    totalLessons: 4,
    completedLessons: 2,
    isExpanded: true,
    lessons: [
      {
        id: 'l5',
        moduleId: 'm2',
        title: 'Типы данных в Python',
        type: 'video',
        duration: '25:10',
        status: 'completed',
        order: 1,
      },
      {
        id: 'l6',
        moduleId: 'm2',
        title: 'Операции с данными',
        type: 'video',
        duration: '18:45',
        status: 'in-progress',
        order: 2,
      },
      {
        id: 'l7',
        moduleId: 'm2',
        title: 'Условные операторы',
        type: 'video',
        duration: '22:30',
        status: 'locked',
        order: 3,
      },
      {
        id: 'l8',
        moduleId: 'm2',
        title: 'ДЗ: Создание калькулятора',
        type: 'homework',
        status: 'locked',
        order: 4,
      },
    ],
  },
  {
    id: 'm3',
    courseId: '1',
    title: 'Циклы и функции',
    order: 3,
    totalLessons: 5,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'l9',
        moduleId: 'm3',
        title: 'Цикл for',
        type: 'video',
        duration: '20:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'l10',
        moduleId: 'm3',
        title: 'Цикл while',
        type: 'video',
        duration: '15:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'l11',
        moduleId: 'm3',
        title: 'Функции в Python',
        type: 'video',
        duration: '28:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'l12',
        moduleId: 'm3',
        title: 'Практика: Работа с функциями',
        type: 'practice',
        duration: '30:00',
        status: 'locked',
        order: 4,
      },
      {
        id: 'l13',
        moduleId: 'm3',
        title: 'ДЗ: Создание игры',
        type: 'homework',
        status: 'locked',
        order: 5,
      },
    ],
  },
  {
    id: 'm4',
    courseId: '1',
    title: 'Объектно-ориентированное программирование',
    order: 4,
    totalLessons: 6,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'l14',
        moduleId: 'm4',
        title: 'Введение в ООП',
        type: 'video',
        duration: '22:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'l15',
        moduleId: 'm4',
        title: 'Классы и объекты',
        type: 'video',
        duration: '30:45',
        status: 'locked',
        order: 2,
      },
      {
        id: 'l16',
        moduleId: 'm4',
        title: 'Наследование',
        type: 'video',
        duration: '25:20',
        status: 'locked',
        order: 3,
      },
      {
        id: 'l17',
        moduleId: 'm4',
        title: 'Инкапсуляция и полиморфизм',
        type: 'video',
        duration: '28:00',
        status: 'locked',
        order: 4,
      },
      {
        id: 'l18',
        moduleId: 'm4',
        title: 'Практика: Создание классов',
        type: 'practice',
        duration: '35:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'l19',
        moduleId: 'm4',
        title: 'Итоговый тест: ООП',
        type: 'test',
        status: 'locked',
        order: 6,
      },
    ],
  },

  // Web-разработка курс
  {
    id: 'w1',
    courseId: '2',
    title: 'Основы HTML',
    order: 1,
    totalLessons: 6,
    completedLessons: 6,
    isExpanded: true,
    lessons: [
      {
        id: 'w1-l1',
        moduleId: 'w1',
        title: 'Введение в HTML и структура документа',
        type: 'video',
        duration: '18:30',
        status: 'completed',
        order: 1,
      },
      {
        id: 'w1-l2',
        moduleId: 'w1',
        title: 'Теги разметки: заголовки, параграфы, списки',
        type: 'video',
        duration: '22:15',
        status: 'completed',
        order: 2,
      },
      {
        id: 'w1-l3',
        moduleId: 'w1',
        title: 'Ссылки и изображения',
        type: 'video',
        duration: '16:45',
        status: 'completed',
        order: 3,
      },
      {
        id: 'w1-l4',
        moduleId: 'w1',
        title: 'Таблицы в HTML',
        type: 'text',
        duration: '12:00',
        status: 'completed',
        order: 4,
      },
      {
        id: 'w1-l5',
        moduleId: 'w1',
        title: 'Практика: Создание первой HTML страницы',
        type: 'practice',
        duration: '25:00',
        status: 'completed',
        order: 5,
      },
      {
        id: 'w1-l6',
        moduleId: 'w1',
        title: 'Тест: Основы HTML',
        type: 'test',
        status: 'completed',
        order: 6,
      },
    ],
  },
  {
    id: 'w2',
    courseId: '2',
    title: 'CSS - каскадные таблицы стилей',
    order: 2,
    totalLessons: 7,
    completedLessons: 4,
    isExpanded: true,
    lessons: [
      {
        id: 'w2-l1',
        moduleId: 'w2',
        title: 'Введение в CSS и способы подключения',
        type: 'video',
        duration: '20:30',
        status: 'completed',
        order: 1,
      },
      {
        id: 'w2-l2',
        moduleId: 'w2',
        title: 'Селекторы и специфичность',
        type: 'video',
        duration: '24:15',
        status: 'completed',
        order: 2,
      },
      {
        id: 'w2-l3',
        moduleId: 'w2',
        title: 'Цвета, фоны и границы',
        type: 'video',
        duration: '19:45',
        status: 'completed',
        order: 3,
      },
      {
        id: 'w2-l4',
        moduleId: 'w2',
        title: 'Блочная модель (Box Model)',
        type: 'video',
        duration: '22:00',
        status: 'in-progress',
        order: 4,
      },
      {
        id: 'w2-l5',
        moduleId: 'w2',
        title: 'Позиционирование элементов',
        type: 'video',
        duration: '26:30',
        status: 'locked',
        order: 5,
      },
      {
        id: 'w2-l6',
        moduleId: 'w2',
        title: 'Практика: Стилизация страницы',
        type: 'practice',
        duration: '30:00',
        status: 'locked',
        order: 6,
      },
      {
        id: 'w2-l7',
        moduleId: 'w2',
        title: 'ДЗ: Создание визитки',
        type: 'homework',
        status: 'locked',
        order: 7,
      },
    ],
  },
  {
    id: 'w3',
    courseId: '2',
    title: 'Flexbox и Grid Layout',
    order: 3,
    totalLessons: 6,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'w3-l1',
        moduleId: 'w3',
        title: 'Введение в Flexbox',
        type: 'video',
        duration: '25:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'w3-l2',
        moduleId: 'w3',
        title: 'Свойства flex-контейнера',
        type: 'video',
        duration: '28:15',
        status: 'locked',
        order: 2,
      },
      {
        id: 'w3-l3',
        moduleId: 'w3',
        title: 'CSS Grid Layout',
        type: 'video',
        duration: '30:45',
        status: 'locked',
        order: 3,
      },
      {
        id: 'w3-l4',
        moduleId: 'w3',
        title: 'Адаптивная верстка',
        type: 'video',
        duration: '32:00',
        status: 'locked',
        order: 4,
      },
      {
        id: 'w3-l5',
        moduleId: 'w3',
        title: 'Практика: Создание макета сайта',
        type: 'practice',
        duration: '40:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'w3-l6',
        moduleId: 'w3',
        title: 'ДЗ: Адаптивный лендинг',
        type: 'homework',
        status: 'locked',
        order: 6,
      },
    ],
  },
  {
    id: 'w4',
    courseId: '2',
    title: 'Основы JavaScript',
    order: 4,
    totalLessons: 8,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'w4-l1',
        moduleId: 'w4',
        title: 'Введение в JavaScript',
        type: 'video',
        duration: '20:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'w4-l2',
        moduleId: 'w4',
        title: 'Переменные и типы данных',
        type: 'video',
        duration: '24:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'w4-l3',
        moduleId: 'w4',
        title: 'Операторы и условия',
        type: 'video',
        duration: '22:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'w4-l4',
        moduleId: 'w4',
        title: 'Циклы в JavaScript',
        type: 'video',
        duration: '19:45',
        status: 'locked',
        order: 4,
      },
      {
        id: 'w4-l5',
        moduleId: 'w4',
        title: 'Функции',
        type: 'video',
        duration: '26:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'w4-l6',
        moduleId: 'w4',
        title: 'Массивы и объекты',
        type: 'video',
        duration: '28:30',
        status: 'locked',
        order: 6,
      },
      {
        id: 'w4-l7',
        moduleId: 'w4',
        title: 'Практика: Интерактивные элементы',
        type: 'practice',
        duration: '35:00',
        status: 'locked',
        order: 7,
      },
      {
        id: 'w4-l8',
        moduleId: 'w4',
        title: 'Тест: Основы JavaScript',
        type: 'test',
        status: 'locked',
        order: 8,
      },
    ],
  },
  {
    id: 'w5',
    courseId: '2',
    title: 'DOM и события',
    order: 5,
    totalLessons: 6,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'w5-l1',
        moduleId: 'w5',
        title: 'Что такое DOM',
        type: 'video',
        duration: '18:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'w5-l2',
        moduleId: 'w5',
        title: 'Поиск и изменение элементов',
        type: 'video',
        duration: '25:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'w5-l3',
        moduleId: 'w5',
        title: 'События и обработчики',
        type: 'video',
        duration: '23:45',
        status: 'locked',
        order: 3,
      },
      {
        id: 'w5-l4',
        moduleId: 'w5',
        title: 'Формы и валидация',
        type: 'video',
        duration: '27:00',
        status: 'locked',
        order: 4,
      },
      {
        id: 'w5-l5',
        moduleId: 'w5',
        title: 'Практика: Интерактивная форма',
        type: 'practice',
        duration: '40:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'w5-l6',
        moduleId: 'w5',
        title: 'Итоговый проект: Одностраничный сайт',
        type: 'homework',
        status: 'locked',
        order: 6,
      },
    ],
  },
  // SQL Основы курс
  {
    id: 'sql-m1',
    courseId: '3',
    title: 'Основы SQL',
    order: 1,
    totalLessons: 5,
    completedLessons: 5,
    isExpanded: true,
    lessons: [
      {
        id: 'sql-m1-l1',
        moduleId: 'sql-m1',
        title: 'Введение в базы данных',
        type: 'video',
        duration: '15:00',
        status: 'completed',
        order: 1,
      },
      {
        id: 'sql-m1-l2',
        moduleId: 'sql-m1',
        title: 'SELECT и базовые запросы',
        type: 'video',
        duration: '20:30',
        status: 'completed',
        order: 2,
      },
      {
        id: 'sql-m1-l3',
        moduleId: 'sql-m1',
        title: 'INSERT, UPDATE, DELETE',
        type: 'video',
        duration: '18:15',
        status: 'completed',
        order: 3,
      },
      {
        id: 'sql-m1-l4',
        moduleId: 'sql-m1',
        title: 'JOIN - объединение таблиц',
        type: 'video',
        duration: '25:00',
        status: 'completed',
        order: 4,
      },
      {
        id: 'sql-m1-l5',
        moduleId: 'sql-m1',
        title: 'Агрегатные функции и GROUP BY',
        type: 'video',
        duration: '22:45',
        status: 'completed',
        order: 5,
      },
    ],
  },
  {
    id: 'sql-m2',
    courseId: '3',
    title: 'Продвинутый SQL',
    order: 2,
    totalLessons: 4,
    completedLessons: 4,
    isExpanded: false,
    lessons: [
      {
        id: 'sql-m2-l1',
        moduleId: 'sql-m2',
        title: 'Подзапросы (Subqueries)',
        type: 'video',
        duration: '24:00',
        status: 'completed',
        order: 1,
      },
      {
        id: 'sql-m2-l2',
        moduleId: 'sql-m2',
        title: 'Индексы и оптимизация',
        type: 'video',
        duration: '26:30',
        status: 'completed',
        order: 2,
      },
      {
        id: 'sql-m2-l3',
        moduleId: 'sql-m2',
        title: 'Транзакции и ACID',
        type: 'video',
        duration: '22:15',
        status: 'completed',
        order: 3,
      },
      {
        id: 'sql-m2-l4',
        moduleId: 'sql-m2',
        title: 'Представления (Views)',
        type: 'video',
        duration: '20:45',
        status: 'completed',
        order: 4,
      },
    ],
  },
  {
    id: 'sql-m3',
    courseId: '3',
    title: 'Работа с PostgreSQL',
    order: 3,
    totalLessons: 3,
    completedLessons: 1,
    isExpanded: true,
    lessons: [
      {
        id: 'sql-m3-l1',
        moduleId: 'sql-m3',
        title: 'Установка и настройка PostgreSQL',
        type: 'video',
        duration: '18:00',
        status: 'completed',
        order: 1,
      },
      {
        id: 'sql-m3-l2',
        moduleId: 'sql-m3',
        title: 'Особенности PostgreSQL',
        type: 'video',
        duration: '23:30',
        status: 'in-progress',
        order: 2,
      },
      {
        id: 'sql-m3-l3',
        moduleId: 'sql-m3',
        title: 'Практический проект: База данных интернет-магазина',
        type: 'practice',
        duration: '35:00',
        status: 'locked',
        order: 3,
      },
    ],
  },
  // React Advanced курс
  {
    id: 'react-m1',
    courseId: '4',
    title: 'React Hooks',
    order: 1,
    totalLessons: 6,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'react-m1-l1',
        moduleId: 'react-m1',
        title: 'Введение в Hooks',
        type: 'video',
        duration: '18:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'react-m1-l2',
        moduleId: 'react-m1',
        title: 'useState и useEffect',
        type: 'video',
        duration: '25:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'react-m1-l3',
        moduleId: 'react-m1',
        title: 'useContext и useReducer',
        type: 'video',
        duration: '22:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'react-m1-l4',
        moduleId: 'react-m1',
        title: 'useMemo и useCallback',
        type: 'video',
        duration: '20:45',
        status: 'locked',
        order: 4,
      },
      {
        id: 'react-m1-l5',
        moduleId: 'react-m1',
        title: 'Custom Hooks',
        type: 'video',
        duration: '24:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'react-m1-l6',
        moduleId: 'react-m1',
        title: 'Практика: Todo App с Hooks',
        type: 'practice',
        duration: '35:00',
        status: 'locked',
        order: 6,
      },
    ],
  },
  // UI/UX дизайн курс
  {
    id: 'ux-m1',
    courseId: '5',
    title: 'Основы UX',
    order: 1,
    totalLessons: 5,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'ux-m1-l1',
        moduleId: 'ux-m1',
        title: 'Что такое UX/UI дизайн',
        type: 'video',
        duration: '16:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'ux-m1-l2',
        moduleId: 'ux-m1',
        title: 'Принципы дизайна интерфейсов',
        type: 'video',
        duration: '22:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'ux-m1-l3',
        moduleId: 'ux-m1',
        title: 'Цвет и типографика',
        type: 'video',
        duration: '20:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'ux-m1-l4',
        moduleId: 'ux-m1',
        title: 'Композиция и сетки',
        type: 'video',
        duration: '24:45',
        status: 'locked',
        order: 4,
      },
      {
        id: 'ux-m1-l5',
        moduleId: 'ux-m1',
        title: 'Прототипирование в Figma',
        type: 'practice',
        duration: '30:00',
        status: 'locked',
        order: 5,
      },
    ],
  },
  // Цифровой маркетинг курс
  {
    id: 'marketing-m1',
    courseId: '6',
    title: 'Основы маркетинга',
    order: 1,
    totalLessons: 5,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'marketing-m1-l1',
        moduleId: 'marketing-m1',
        title: 'Введение в цифровой маркетинг',
        type: 'video',
        duration: '18:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'marketing-m1-l2',
        moduleId: 'marketing-m1',
        title: 'SEO оптимизация',
        type: 'video',
        duration: '25:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'marketing-m1-l3',
        moduleId: 'marketing-m1',
        title: 'Контекстная реклама',
        type: 'video',
        duration: '22:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'marketing-m1-l4',
        moduleId: 'marketing-m1',
        title: 'SMM и работа с соцсетями',
        type: 'video',
        duration: '24:00',
        status: 'locked',
        order: 4,
      },
      {
        id: 'marketing-m1-l5',
        moduleId: 'marketing-m1',
        title: 'Email маркетинг',
        type: 'video',
        duration: '20:45',
        status: 'locked',
        order: 5,
      },
    ],
  },
  // Управление проектами курс
  {
    id: 'pm-m1',
    courseId: '7',
    title: 'Agile и Scrum',
    order: 1,
    totalLessons: 5,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'pm-m1-l1',
        moduleId: 'pm-m1',
        title: 'Введение в управление проектами',
        type: 'video',
        duration: '17:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'pm-m1-l2',
        moduleId: 'pm-m1',
        title: 'Методология Agile',
        type: 'video',
        duration: '23:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'pm-m1-l3',
        moduleId: 'pm-m1',
        title: 'Scrum фреймворк',
        type: 'video',
        duration: '26:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'pm-m1-l4',
        moduleId: 'pm-m1',
        title: 'Kanban и управление задачами',
        type: 'video',
        duration: '21:45',
        status: 'locked',
        order: 4,
      },
      {
        id: 'pm-m1-l5',
        moduleId: 'pm-m1',
        title: 'Работа с командой',
        type: 'video',
        duration: '25:00',
        status: 'locked',
        order: 5,
      },
    ],
  },
  // Machine Learning курс
  {
    id: 'ml-m1',
    courseId: '8',
    title: 'Введение в ML',
    order: 1,
    totalLessons: 6,
    completedLessons: 0,
    isExpanded: false,
    lessons: [
      {
        id: 'ml-m1-l1',
        moduleId: 'ml-m1',
        title: 'Что такое Machine Learning',
        type: 'video',
        duration: '20:00',
        status: 'locked',
        order: 1,
      },
      {
        id: 'ml-m1-l2',
        moduleId: 'ml-m1',
        title: 'Типы машинного обучения',
        type: 'video',
        duration: '24:30',
        status: 'locked',
        order: 2,
      },
      {
        id: 'ml-m1-l3',
        moduleId: 'ml-m1',
        title: 'NumPy и Pandas',
        type: 'video',
        duration: '28:15',
        status: 'locked',
        order: 3,
      },
      {
        id: 'ml-m1-l4',
        moduleId: 'ml-m1',
        title: 'Линейная регрессия',
        type: 'video',
        duration: '30:45',
        status: 'locked',
        order: 4,
      },
      {
        id: 'ml-m1-l5',
        moduleId: 'ml-m1',
        title: 'Классификация данных',
        type: 'video',
        duration: '27:00',
        status: 'locked',
        order: 5,
      },
      {
        id: 'ml-m1-l6',
        moduleId: 'ml-m1',
        title: 'Практика: Первая ML модель',
        type: 'practice',
        duration: '40:00',
        status: 'locked',
        order: 6,
      },
    ],
  },
];

export const mockHomework: Homework[] = [
  // ДЗ #1 - Выполнено (отличная оценка)
  {
    id: 'hw-python-1',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #1: Основы синтаксиса',
    description: 'Напишите программу для работы с базовыми типами данных и выводом информации',
    deadline: '2025-10-05T23:59:00Z',
    maxGrade: 100,
    status: 'graded',
    grade: 95,
    feedback: 'Отличная работа! Программа работает корректно, код чистый и читаемый.',
    submittedAt: '2025-10-04T18:30:00Z',
    gradedAt: '2025-10-05T10:15:00Z',
    attempts: 1,
    maxAttempts: 3,
  },
  // ДЗ #2 - Выполнено (хорошая оценка)
  {
    id: 'hw-python-2',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #2: Калькулятор',
    description: 'Создайте простой калькулятор с базовыми арифметическими операциями',
    deadline: '2025-10-12T23:59:00Z',
    maxGrade: 100,
    status: 'graded',
    grade: 82,
    feedback: 'Хорошая работа! Калькулятор работает корректно, но есть замечания.',
    submittedAt: '2025-10-12T20:15:00Z',
    gradedAt: '2025-10-13T09:30:00Z',
    attempts: 1,
    maxAttempts: 3,
  },
  // ДЗ #3 - Выполнено (средняя оценка)
  {
    id: 'hw-python-3',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #3: Угадай число',
    description: 'Создайте игру "Угадай число" с использованием циклов и условий',
    deadline: '2025-10-19T23:59:00Z',
    maxGrade: 100,
    status: 'graded',
    grade: 70,
    feedback: 'Базовая реализация работает, но есть существенные недочеты.',
    submittedAt: '2025-10-19T22:45:00Z',
    gradedAt: '2025-10-20T11:00:00Z',
    attempts: 1,
    maxAttempts: 3,
  },
  // ДЗ #4 - На проверке
  {
    id: 'hw-python-4',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #4: Работа с функциями',
    description: 'Создайте набор функций для работы со списками',
    deadline: '2025-11-26T23:59:00Z',
    maxGrade: 100,
    status: 'submitted',
    submittedAt: '2025-11-25T14:30:00Z',
    attempts: 1,
    maxAttempts: 3,
  },
  // ДЗ #5 - В процессе
  {
    id: 'hw-python-5',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #5: Телефонная книга',
    description: 'Создайте программу для управления телефонной книгой с использованием словарей',
    deadline: '2025-12-01T23:59:00Z',
    maxGrade: 100,
    status: 'in-progress',
    attempts: 0,
    maxAttempts: 3,
  },
  // ДЗ #6 - Не начато
  {
    id: 'hw-python-6',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #6: Система управления студентами',
    description: 'Создайте систему для управления информацией о студентах с использованием классов',
    deadline: '2025-12-08T23:59:00Z',
    maxGrade: 100,
    status: 'not-started',
    attempts: 0,
    maxAttempts: 3,
  },
  // ДЗ #7 - Просрочено
  {
    id: 'hw-python-7',
    courseId: '1',
    courseName: 'Python для начинающих',
    title: 'ДЗ #7: Анализатор текста',
    description: 'Создайте программу для анализа текста (подсчет слов, символов и т.д.)',
    deadline: '2025-11-22T23:59:00Z',
    maxGrade: 100,
    status: 'not-started',
    attempts: 0,
    maxAttempts: 2,
  },
  // Web-разработка ДЗ
  {
    id: 'hw-web-1',
    courseId: '2',
    courseName: 'Web-разработка',
    title: 'ДЗ #3: Верстка лендинга',
    description: 'Создайте адаптивную страницу лендинга используя HTML и CSS',
    deadline: '2025-12-04T23:59:00Z',
    maxGrade: 100,
    status: 'not-started',
    attempts: 0,
    maxAttempts: 2,
  },
];

export const mockGrades: CourseGrades[] = [
  {
    courseId: '1',
    courseName: 'Python для начинающих',
    teacherName: 'Андрей Петров',
    progress: 65,
    averageGrade: 82,
    homeworks: [
      {
        id: 'g1',
        homeworkId: 'hw1',
        homeworkTitle: 'ДЗ #1: Основы',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 90,
        maxGrade: 100,
        percentage: 90,
        gradedAt: '2025-10-05T10:00:00Z',
      },
      {
        id: 'g2',
        homeworkId: 'hw2',
        homeworkTitle: 'ДЗ #2: Переменные',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 85,
        maxGrade: 100,
        percentage: 85,
        gradedAt: '2025-10-12T10:00:00Z',
      },
      {
        id: 'g3',
        homeworkId: 'hw3',
        homeworkTitle: 'ДЗ #3: Условия',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 78,
        maxGrade: 100,
        percentage: 78,
        gradedAt: '2025-10-19T10:00:00Z',
      },
      {
        id: 'g4',
        homeworkId: 'hw4',
        homeworkTitle: 'ДЗ #4: Функции',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 85,
        maxGrade: 100,
        percentage: 85,
        gradedAt: '2025-10-26T10:00:00Z',
      },
    ],
    tests: [
      {
        id: 't1',
        homeworkId: 'test1',
        homeworkTitle: 'Тест #1: Основы',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 95,
        maxGrade: 100,
        percentage: 95,
        gradedAt: '2025-10-08T10:00:00Z',
      },
      {
        id: 't2',
        homeworkId: 'test2',
        homeworkTitle: 'Тест #2: Условия и циклы',
        courseId: '1',
        courseName: 'Python для начинающих',
        grade: 88,
        maxGrade: 100,
        percentage: 88,
        gradedAt: '2025-10-20T10:00:00Z',
      },
    ],
  },
  {
    courseId: '2',
    courseName: 'Web-разработка',
    teacherName: 'Мария Сидорова',
    progress: 40,
    averageGrade: 88,
    homeworks: [
      {
        id: 'g5',
        homeworkId: 'hw5',
        homeworkTitle: 'ДЗ #1: HTML Основы',
        courseId: '2',
        courseName: 'Web-разработка',
        grade: 92,
        maxGrade: 100,
        percentage: 92,
        gradedAt: '2025-10-10T10:00:00Z',
      },
      {
        id: 'g6',
        homeworkId: 'hw6',
        homeworkTitle: 'ДЗ #2: CSS Стили',
        courseId: '2',
        courseName: 'Web-разработка',
        grade: 85,
        maxGrade: 100,
        percentage: 85,
        gradedAt: '2025-10-17T10:00:00Z',
      },
    ],
    tests: [],
  },
];

export const mockStatistics: UserStatistics = {
  activeCourses: 3,
  completedCourses: 2,
  totalHomeworks: 15,
  completedHomeworks: 12,
  totalTests: 10,
  completedTests: 8,
  averageGrade: 85,
  streak: 8,
  totalStudyTime: 45,
  registeredAt: '2025-09-01T00:00:00Z',
};

export const mockProgressData: ProgressDataPoint[] = [
  { week: 'Нед1', value: 25 },
  { week: 'Нед2', value: 35 },
  { week: 'Нед3', value: 50 },
  { week: 'Нед4', value: 60 },
  { week: 'Нед5', value: 70 },
  { week: 'Нед6', value: 75 },
  { week: 'Нед7', value: 85 },
  { week: 'Нед8', value: 90 },
];

export const mockAchievements: Achievement[] = [
  {
    id: 'a1',
    title: 'Первый курс',
    description: 'Записались на первый курс',
    icon: '🏆',
    isUnlocked: true,
    unlockedAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'a2',
    title: '10 заданий',
    description: 'Выполнили 10 заданий',
    icon: '📚',
    isUnlocked: true,
    unlockedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'a3',
    title: 'Отличник',
    description: 'Средний балл выше 85',
    icon: '⭐',
    isUnlocked: true,
    unlockedAt: '2025-11-01T00:00:00Z',
  },
  {
    id: 'a4',
    title: 'Streak 7 дней',
    description: 'Учились 7 дней подряд',
    icon: '🔥',
    isUnlocked: true,
    unlockedAt: '2025-11-20T00:00:00Z',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act1',
    type: 'homework_submitted',
    title: 'Отправлено ДЗ #5',
    timestamp: '2025-11-28T14:30:00Z',
  },
  {
    id: 'act2',
    type: 'lesson_completed',
    title: 'Завершен урок 2.2',
    timestamp: '2025-11-27T20:15:00Z',
  },
  {
    id: 'act3',
    type: 'course_started',
    title: 'Начат курс SQL',
    timestamp: '2025-11-26T18:45:00Z',
  },
  {
    id: 'act4',
    type: 'grade_received',
    title: 'Проверено ДЗ #4',
    timestamp: '2025-11-25T16:20:00Z',
  },
];

export const mockDashboardData: DashboardData = {
  user: mockUser,
  statistics: mockStatistics,
  continueLearning: mockCourses[0],
  upcomingDeadlines: mockHomework.filter(hw => hw.status !== 'graded').slice(0, 2),
  myCourses: mockCourses,
  recommendedCourses: [
    {
      id: 'r1',
      title: 'Django для веб-разработки',
      description: 'Создавайте веб-приложения с Django',
      coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
      teacherId: 't4',
      teacherName: 'Алексей Смирнов',
      progress: 0,
      totalModules: 6,
      completedModules: 0,
      isActive: false,
      startDate: '',
    },
    {
      id: 'r2',
      title: 'React для начинающих',
      description: 'Изучите React и создавайте SPA',
      coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
      teacherId: 't5',
      teacherName: 'Елена Попова',
      progress: 0,
      totalModules: 5,
      completedModules: 0,
      isActive: false,
      startDate: '',
    },
  ],
  recentActivity: mockActivities,
};

export const mockFeaturedCourses: SliderItem[] = [
  {
    id: '1', // Python для начинающих
    title: 'Python для начинающих',
    description: 'Изучите основы Python и научитесь писать код',
    image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200',
    badge: 'Топ курс',
  },
  {
    id: '8', // Machine Learning с Python
    title: 'Machine Learning с Python',
    description: 'Введение в машинное обучение и нейронные сети',
    image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1200',
    badge: 'Новинка',
  },
  {
    id: '2', // Web-разработка
    title: 'Web-разработка',
    description: 'HTML, CSS, JavaScript - создайте свой первый сайт',
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1200',
    badge: 'Популярный',
  },
  {
    id: '4', // React Advanced
    title: 'React Advanced',
    description: 'Продвинутые техники разработки на React',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200',
    badge: 'Актуально',
  },
  {
    id: '3', // SQL Основы
    title: 'SQL Основы',
    description: 'Работа с базами данных и SQL запросами',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=1200',
    badge: 'Востребовано',
  },
];
